name: arm-gcc

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        app: [hid-keyboard, hid-mouse]
        board: [frdmk22f]
        preset: [release]
    runs-on: ${{ matrix.os }}
    env:
      ARM_GCC_DIR: /usr
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install west
        run: pip3 install --user -U west

      - name: Install python dependencies of scripts
        run: pip3 install -r scripts/requirements.txt

      - name: Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: West init
        run: west init -l .

      - name: Fetch SDK
        run: west update && west patch

      - name: Install build dependencies
        run: sudo apt-get install -y gcc-arm-none-eabi

      - name: Build firmware
        working-directory: ${{ matrix.app }}
        run: |
          BOARD=${{ matrix.board }} west build -d ${{ matrix.preset }} -- --preset ${{ matrix.preset }}

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.app }}
          path: ${{ matrix.app }}/${{ matrix.preset }}/${{ matrix.app }}.elf
